package com.icabank.pages;

import com.icabank.utilities.Driver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.FindBy;
import org.openqa.selenium.support.PageFactory;

public abstract class BasePage {


    @FindBy(xpath = "//*[@id=\"root\"]/div[1]/div[2]/div/div[2]/button[1]")
    public WebElement cookiesAccept;

    @FindBy(xpath = "//*[@id=\"mainHeader\"]/div/div/a[2]")
    public WebElement mobileMenu;

    @FindBy(xpath = "//*[@id=\"root\"]/div/div[1]/div/nav/div[1]/div[1]/a")
    public WebElement lanaPage;

    @FindBy(xpath = "//*[@id=\"root\"]/div/div[1]/div[1]/div[2]/div/div[1]/div[1]/a")
    public WebElement mobSeLana;

    @FindBy(xpath = "//*[@id=\"root\"]/div/div[1]/div/nav/div[1]/div[2]/a")
    public WebElement kortBetalaPage;

    @FindBy(xpath = "//*[@id=\"root\"]/div/div[1]/div[1]/div[3]/div/div[1]/div[1]/a")
    public WebElement mobSeKortBetala;

    @FindBy(xpath = "//*[@id=\"root\"]/div/div[1]/div/nav/div[1]/div[3]/a")
    public WebElement sparaPage;

    @FindBy(xpath = "//*[@id=\"root\"]/div/div[1]/div[1]/div[4]/div/div[1]/div[1]/a")
    public WebElement mobSeSpara;

    @FindBy(xpath = "//*[@id=\"root\"]/div/div[1]/div/nav/div[1]/div[4]/a")
    public WebElement forsakraPage;

    @FindBy(xpath = "//*[@id=\"root\"]/div/div[1]/div[1]/div[5]/div/div[1]/div[1]/a")
    public WebElement mobSeForsakra;

    @FindBy(xpath = "//*[@id=\"root\"]/div/div[1]/div/nav/div[1]/div[6]/a")
    public WebElement varaTipsPage;

    @FindBy(xpath = "//*[@id=\"root\"]/div/div[1]/div/nav/div[1]/div[7]/a")
    public WebElement kundservicePage;

    @FindBy(xpath = "//*[@id=\"root\"]/div/div[1]/div/nav/div[1]/div[9]/a")
    public WebElement bliBankkundPage;

    @FindBy(xpath = "//*[@id=\"mainHeader\"]/div/div/button")
    public WebElement loginPage;

    @FindBy(xpath = "//*[@id=\"searchHeaderButton\"]")
    public WebElement sokPage;

    @FindBy(xpath = "//*[@id=\"root\"]/div/div[1]/div[1]/nav/div[1]/div[8]")
    public WebElement mobSokPage;

    @FindBy(xpath = "//*[@id=\"AutoGenerated_footer_navigation\"]/div/div[1]/div[1]/span")
    public WebElement varaTjansterFunc;

    @FindBy(xpath = "//*[@id=\"AutoGenerated_footer_navigation\"]/div/div[2]/div[1]/span")
    public WebElement omIcaBankenFunc;

    @FindBy(xpath = "//*[@id=\"AutoGenerated_footer_navigation\"]/div/div[3]/div[1]/span")
    public WebElement sakerhetVillkorFunc;

    @FindBy(xpath = "//*[@id=\"AutoGenerated_footer_navigation\"]/div/div[4]/div[1]/span")
    public WebElement socialaMedierFunc;

    @FindBy(xpath = "//*[@id=\"AutoGenerated_footer_navigation\"]/div/div[5]/div[1]/span")
    public WebElement icaBankensAppFunc;

    public BasePage() {
        PageFactory.initElements(Driver.get(), this);
    }



}
